### ISSUE TITLE
[e2e] Failing test periodic-image-builder-gcp-all-nightly

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-gcp#1017]
/kind failing-test
/help
/priority critical-urgent

**What steps did you take and what happened:**

The [periodic-image-builder-gcp-all-nightly](https://testgrid.k8s.io/sig-cluster-lifecycle-image-builder#periodic-image-builder-gcp-all-nightly) has been failing the last couple of days.

Looking at the logs there is this error: `no available installation candidate for kubelet=1.24.15-00`

**What did you expect to happen:**

We need to get the tests green again.

**Comment by furkatgofurov7** [comment]
Briefly checked it and the failure is due to a [recent announcement](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/) in upstream that `pkgs.k8s.io` should be used instead of apt.kubernetes.io (or yum.kubernetes.io.)

We need to do something similar to what https://github.com/kubernetes-sigs/image-builder/pull/1280 does

**Comment by richardcase** [comment]
Thanks @furkatgofurov7 , that makes sense looking at the error message and timing of the start of the failures.

The change in https://github.com/kubernetes-sigs/image-builder/pull/1280 should solve this issue as the job is running in the context of image-builder and this change appears to be for all images.

**Comment by furkatgofurov7** [comment]
@richardcase true, the run already using the new package repo but the format of k8s deb/rpm images in https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/packer/gce/ci/nightly/overwrite-1-24.json are not correct. I will open a PR to fix them. 

/assign

**Comment by furkatgofurov7** [comment]
/reopen

I'll wait for the next run to be green and make sure it is fixed, and then close it

**Comment by cpanato** [comment]
retrigger the job to force a new run and double check

thanks for the fix @furkatgofurov7

**Comment by furkatgofurov7** [comment]
> retrigger the job to force a new run and double check

Two consecutive green runs, closing it now

/close
