### ISSUE TITLE
Support multiple GKE configurations in GCPManagedControlPlane

### ISSUE THREAD

**Issue by dantiandb** [kubernetes-sigs/cluster-api-provider-gcp#1023]
/kind feature

**Describe the solution you'd like**
CAPG should support the following features provided by GKE
- `ClusterIpv4Cidr` (as defined in [containerpb.Cluster](https://pkg.go.dev/cloud.google.com/go/container/apiv1/containerpb#Cluster))
- AddonsConfig
  - [DnsCacheConfig](https://cloud.google.com/kubernetes-engine/docs/how-to/nodelocal-dns-cache#:~:text=NodeLocal%20DNSCache%20is%20a%20GKE,same%20node%20as%20the%20Pod.)
  - [GcePersistentDiskCsiDriverConfig](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver)
- [ ResourceLabels](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-managing-labels)
- IPAllocationPolicy (as defined in [containerpb.IPAllocationPolicy](https://pkg.go.dev/cloud.google.com/go/container/apiv1/containerpb#IPAllocationPolicy))
   - UseIpAliases
   - ClusterSecondaryRangeName
   - ServicesSecondaryRangeName
   - ClusterIpv4CidrBlock
   - ServicesIpv4CidrBlock
- [MaintenancePolicy](https://cloud.google.com/kubernetes-engine/docs/how-to/maintenance-windows-and-exclusions)
- NetworkConfig (as defined in [containerpb.NetworkConfig](https://pkg.go.dev/cloud.google.com/go/container/apiv1/containerpb#NetworkConfig))
   - DnsConfig
   - DatapathProvider
- [DefaultMaxPodsConstraint](https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr#:~:text=MAXIMUM_PODS%20%3A%20the%20default%20maximum%20number,the%20default%20value%20of%20110%20.)
- [PrivateClusterConfig](https://www.google.com/search?q=private+cluster+gke&sourceid=chrome&ie=UTF-8)
- [ShieldedNodes](https://cloud.google.com/kubernetes-engine/docs/how-to/shielded-gke-nodes)
- [WorkloadIdentityConfig](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)
- [LoggingConfig](https://cloud.google.com/stackdriver/docs/solutions/gke/managing-logs)

**Anything else you would like to add:**
Feature support is scoped to what is supported by the GCP containerpb SDK https://pkg.go.dev/cloud.google.com/go/container/apiv1/containerpb

**Comment by richardcase** [comment]
We also have an existing issue #906
