### ISSUE TITLE
New release plans with CAPI 1.5.0

### ISSUE THREAD

**Issue by damdo** [kubernetes-sigs/cluster-api-provider-gcp#1031]
/kind feature

Describe the solution you'd like
I was wondering if there are any plans in regards to releasing a newer minor or patch release to cover [the bump in k8s and core CAPI dependencies](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/985) given that they have been merged for a bit.

Thanks!

cc. @richardcase @cpanato @dims

**Comment by richardcase** [comment]
We could do a 1.5.0 release to keep inline with CAPG matching the CAPI release series.

@cpanato - i can do the release if you want?

**Comment by cpanato** [comment]
I would first we fix the ci artifacts conformance tests, that i am trying here https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1018 and then we can run a release

**Comment by richardcase** [comment]
Good point @cpanato. I can take a look at the conformance tests tomorrow as well.

**Comment by cpanato** [comment]
> Good point @cpanato. I can take a look at the conformance tests tomorrow as well.

ping me over slack and lets discuss, thank you so much

**Comment by damdo** [comment]
@cpanato any luck on the conformance test you were looking at?

**Comment by cpanato** [comment]
not yet :/

**Comment by damdo** [comment]
@cpanato I see you were able to make those test passing, and now https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1018 merged 🎉 
This unblocks the release right? :)

**Comment by damdo** [comment]
Looks like `1.5.0` is out, thanks @cpanato !
