### ISSUE TITLE
Allow specifying the minimum CPU platform in GCPMachine spec

### ISSUE THREAD

**Issue by itspngu** [kubernetes-sigs/cluster-api-provider-gcp#1040]
/kind feature

**Describe the solution you'd like**
The GCPMachine spec allows specifying machine types, but some setups necessitate requesting a certain minimum CPU platform. This should be an optional field in the GCPMachine spec.

**Anything else you would like to add:**
GCP docs: https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform#rest_1

**Comment by jayesh-srivastava** [comment]
Hi @itspngu , is this still open, if yes then I can take this up.

**Comment by itspngu** [comment]
> Hi @itspngu , is this still open, if yes then I can take this up.

Hey @jayesh-srivastava! Yes, I just currently lack the time to work on it - feel free and thank you :)

**Comment by tasdikrahman** [comment]
Hello @jayesh-srivastava , was wondering if you're still working on this.
