### ISSUE TITLE
Improve documentation on E2E tests

### ISSUE THREAD

**Issue by salasberryfin** [kubernetes-sigs/cluster-api-provider-gcp#1080]
/kind documentation

**Describe the solution you'd like**
While working on #1053, I've encountered a few obstacles to run E2E tests locally and I haven't found the documentation to be very detailed on how E2E tests are actually structured and how to use them as a developer. Thanks to @richardcase, I've been able to identify a few things missing from my configuration but I think it would be great, especially for new or relatively new contributors, to have a nuanced, easy to follow documentation on how CAPG E2E tests are structured and how a user can leverage them to improve their development experience.

**Anything else you would like to add:**

[This](https://capz.sigs.k8s.io/developers/development.html#e2e-testing) is the E2E section from the CAPZ book which can be used as a reference.

**Comment by professorabhay** [comment]
Hey @salasberryfin, Can I do this?

**Comment by salasberryfin** [comment]
Hey @professorabhay, thanks for volunteering to work on this. It would be better to have confirmation from any of the `cluster-api-gcp-maintainers` @richardcase @cpanato @dims.
