### ISSUE TITLE
Internal Only LoadBalancer doesn't pass healthcheck out of the box.

### ISSUE THREAD

**Issue by jwmay2012** [kubernetes-sigs/cluster-api-provider-gcp#1256]
/kind bug

**What steps did you take and what happened:**
I'm having an issue with the `Internal` only loadbalancer type. When cluster-api brings everything up, the LB never passes the healthcheck.

I've confirmed the node becomes healthy via local `curl https://localhost:6443/readyz -k` which responds `ok`.

I can get the LB to be healthy by:
- deleting the "frontend/Forwardingrule" and allowing CAPG to recreate it. immediately healthy when it is recreated.
- OR manually creating a second internal passthrough LB, identically configured (or slightly different, but 'correct') to the one created by CAPG. Both LB's become healthy. After deleting the new LB, the original stays healthy.

Seems super weird. Creating a new identical frontend/forwardingrule or recreating the old one causes the healthcheck to start passing and the LB to start accepting requests. 

**What did you expect to happen:**

I expect the Internal Only LB to pass the healthcheck on its own and become accessible at the frontend internal subnet IP address.

**Anything else you would like to add:**
This is for a 1 node cluster.

Testing the code from https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1222
Tagging @bfournie as original author.

**Environment:**

- Cluster-api version: commit f6f58a4bea8dae7a294c28481fb3740f75df8e00
- Minikube/KIND version: kind v0.22.0 go1.21.7 darwin/arm64
- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```
- OS (e.g. from `/etc/os-release`): Darwin Kernel Version 23.5.0

**Comment by jwmay2012** [comment]
When using `loadBalancerType: InternalExternal` the External works, and the Internal doesn't. The Internal will become healthy when I do the same things mentioned in the original issue.

**Comment by bfournie** [comment]
@jwmay2012 I have not been able to duplicate this problem in my setup. However, I wonder if its due to the different type of health check that is created for the internal LB.  For the internal LB a regional HealthCheck in a particular region is being created, which is different than the external LB which creates a global HealthCheck. It may be that the region is not ready when the HealthCheck is initially run.

We can change this to a global health check if you could try it out, e.g. here using `createOrGetHealthCheck() `https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/cloud/services/compute/loadbalancers/reconcile.go#L220

**Comment by jwmay2012** [comment]
The `Internal` Load Balancer works. Found the issue in my custom clusters `.yaml`.

I had some custom DNS tweaks to the `netplan`.

```
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
spec:
  template:
    spec:
      files:
      - path: /etc/netplan/99-custom-dns.yaml
        content: |
          <custom netplan>
      preKubeadmCommands:
      - netplan apply
```
Same for `KubeadmControlPlane`.

Internal Passthrough Load Balancers work by creating a route on the VMs to handle direct responses to clients.
https://cloud.google.com/load-balancing/docs/internal
> Unlike a proxy load balancer, an internal passthrough Network Load Balancer doesn't terminate connections from clients and then open new connections to backends. Instead, an internal passthrough Network Load Balancer routes connections directly from clients to the healthy backends, without any interruption. Responses from the healthy backend VMs go directly to the clients, not back through the load balancer. TCP responses use direct server return.

> The Google Cloud [Linux guest environment](https://cloud.google.com/compute/docs/instances/linux-guest-environment), [Windows guest environment](https://github.com/GoogleCloudPlatform/compute-image-windows), or an equivalent process configures each backend VM with the IP address of the load balancer. For VMs created from Google Cloud images, the [Guest agent](https://cloud.google.com/compute/docs/images/guest-environment) (formerly, the Windows Guest Environment or Linux Guest Environment) installs the local route for the load balancer's IP address.

>When a backend VM receives a load-balanced packet from a client, the packet's source and destination are:

>Source: the client's internal IPv4, IPv6, or the IPv4 address from one of the client's alias IPv4 ranges.
Destination: the IP address of the load balancer's forwarding rule. The forwarding rule uses either a single [internal IPv4 address](https://cloud.google.com/vpc/docs/subnets#valid-ranges) or an [internal IPv6 range](https://cloud.google.com/vpc/docs/subnets#ipv6-ranges).
Because the load balancer is a pass-through load balancer (not a proxy), packets arrive bearing the destination IP address of the load balancer's forwarding rule.

A VM with a working LB has this route.
```
root@foo-control-plane-4fqr6:/root# ip route show table local
local 10.228.12.18 dev ens4 proto 66 scope host
...
```

My broken VMs with unhealthy Internal Passthrough LBs do not have this route.


The route gets added by the `google-guest-agent.service` [here](https://github.com/GoogleCloudPlatform/guest-agent/blob/main/google_guest_agent/addresses.go#L163).
But the [trigger to run are events from GCP](https://github.com/GoogleCloudPlatform/guest-agent/blob/main/google_guest_agent/main.go#L226).

When triggered, LB forwarding IPs are pulled from 
```
curl -L -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/forwarded-ips/0
```
`netplan apply` breaks DNS for 2-3 seconds.

So what I have here is a race condition between `netplan apply` and this metadata pull from the LB startup event, which fails when `metadata.google.internal` doesn't resolve. 
We can force a metadata refresh and apply on `google-guest-agent` startup.

This explains why the initial LB frontend never gets healthy, but any additional frontend creation or re-creation fixes it. A new event is sent to the guest agent and appropriate routes get added.

This was my fix:
```
preKubeadmCommands:
    - netplan apply
    - while [[ -z $(dig metadata.google.internal +short) ]]; do sleep 1; done
    - systemctl restart google-guest-agent.service
```

Thanks @bfournie for making the Internal LB feature and for looking into this.

**Comment by bfournie** [comment]
Thanks @jwmay2012 for testing this
