### ISSUE TITLE
Control-plane endpoint templating wrong port

### ISSUE THREAD

**Issue by BrennenMM7** [kubernetes-sigs/cluster-api-provider-gcp#1273]
/kind bug
Hey guys, there is a bug in the new CAPG 1.7.0 release for internal load balancers. What seems to be occurring is that the internal forwarding rule is statically set to create ports for 6443 & 22623. However the API server control-plane endpoint is being forced to template with 443 so nodes are unable to join the cluster or communicate with the API server.

[LoadBalancer Templating](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/v1.7.0/cloud/services/compute/loadbalancers/reconcile.go#L594)
[ControlPlane Endpoint Templating](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/v1.7.0/cloud/scope/cluster.go#L166)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Simply create a new CAPG cluster with an internal loadbalancer/endpoint. 

**What did you expect to happen:**
Expected to see the forward rule match the controlplane endpoint port

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 1.7.1
- Minikube/KIND version: Kind 0.23.0
- Kubernetes version: (use `kubectl version`): 1.27.X
- OS (e.g. from `/etc/os-release`): Ubuntu 2204

**Comment by bfournie** [comment]
Yes, this should match the cluster APIServerPort. We've been testing with APIServerPort set to 6443 so didn't catch the problem. Will create a PR for this
