### ISSUE TITLE
Add GCP to the Cluster API Quick Start

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-gcp#151]
/kind documentation
/help

**Describe the solution you'd like**
We need to document every step and requirement needed as part of this effort and when ready, we need to PR the upstream repository to add new tabs to this page https://cluster-api.sigs.k8s.io/user/quick-start.html.

**Comment by sb1975** [comment]
I agree, at least some basic steps need to be there to even attempt unless you are expert in the code and understand the flow very well already..

**Comment by sb1975** [comment]
I suppose GCP is nowhere..

**Comment by sayantani11** [comment]
@vincepri If the issue is open I will be more than happy to take this.

**Comment by sayantani11** [comment]
@vincepri @randomvariable I guess the issue is resolved went through the Quick Start section of the book
