### ISSUE TITLE
Build images doesnt work

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api-provider-gcp#153]
/kind bug
root@capd-2:~/image-builder/images/capi/packer/gce# make build-gce-default
make: *** No rule to make target 'build-gce-default'.  Stop.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by alejandrox1** [comment]
I'd like to take a look at this
/assign

**Comment by dims** [comment]
packer+ansible does not work when running as root. please run as a regular user

/close
