### ISSUE TITLE
Error when creating machines b/c of k8s version

### ISSUE THREAD

**Issue by rsmitty** [kubernetes-sigs/cluster-api-provider-gcp#156]
/kind bug

**What steps did you take and what happened:**
The examples that get generated don't work out of the box once you create the controlplane. This seems to be failing on the semver parsing of the kubernetes version, specifically because of the leading `v`. Here's the error I encountered:

```
E0913 13:50:43.730099       1 controller.go:218] controller-runtime/controller "msg"="Reconciler
 error" "error"="failed to create GCPMachine instance: error parsing Spec.Version on Machine 
\"test1-controlplane-0\" in namespace \"default\", expected valid SemVer string: Invalid character(s) 
found in major number \"v1\""  "controller"="gcpmachine" "request"=
{"Namespace":"default","Name":"test1-controlplane-0"}
```

**What did you expect to happen:**

Control plane gets created.

**Anything else you would like to add:**

We don't make use of this value in the talos provider, so I can't really say whether the `v` is required in the kubeadm bootstrapper code, but removing it seems to cause the machine creation to pass the semver check. Will follow this issue with a PR of the small change.

**Comment by jdef** [comment]
once the semver problem is fixed, the default machine family name (a few dozen lines down) is also not going to match up. I had to inject a "v" prior to the major version, so my family generator looks like this now:
```go
"projects/%s/global/images/family/capi-ubuntu-1804-k8s-v%d-%d"
```

**Comment by vincepri** [comment]
Thanks @jdef, @rsmitty do you think you could fix that as well as part of your PR?

**Comment by rsmitty** [comment]
sure, on it.
