### ISSUE TITLE
Rewrite generate-yaml.sh as a go program

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes-sigs/cluster-api-provider-gcp#19]
_From @spew on May 25, 2018 20:0_

The generate-yaml.sh bash script is growing in scope and complexity. We should rewrite it as a go program to make it easier for development as well as testing.

_Copied from original issue: kubernetes-sigs/cluster-api#216_

**Comment by roberthbailey** [comment]
_From @karan on May 29, 2018 17:15_

+1

**Comment by roberthbailey** [comment]
Alternatively, we should move the complex logic into the gcp cluster controller and make it just set env vars like project / zone.

**Comment by spew** [comment]
Agree that the better solution is to move everything into the controllers.
