### ISSUE TITLE
timeout command not available on mac os 

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-gcp#271]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- running `make create-cluster` gives an error about the timeout command not available on mac os 

**What did you expect to happen:**
To be able to execute the commands that would create the test cluster

**Comment by nader-ziada** [comment]
one workaround I used is the following:
```
brew install coreutils
sudo ln -s /usr/local/bin/gtimeout /usr/local/bin/timeout
```

**Comment by vincepri** [comment]
Maybe we should add `coreutils` for mac users in the quick start?

**Comment by nader-ziada** [comment]
Yeah, just a doc update somewhere. Wasn’t sure what the best place is
