### ISSUE TITLE
Update release to v0.3.0

### ISSUE THREAD

**Issue by aa250816** [kubernetes-sigs/cluster-api-provider-gcp#302]
/kind feature

**Describe the solution you'd like**
Release an update for compatibility with cluster api v0.3.0 https://cluster-api.sigs.k8s.io/developer/providers/v1alpha2-to-v1alpha3.html.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by detiber** [comment]
This has now been done
/close
