### ISSUE TITLE
cluster-api-provider-gcp not working

### ISSUE THREAD

**Issue by sb1975** [kubernetes-sigs/cluster-api-provider-gcp#306]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
git clone https://github.com/kubernetes-sigs/cluster-api.git
make clusterctl
cd cluster-api
cat > clusterctl-settings.json <<EOF
{
  "providers": ["cluster-api","bootstrap-kubeadm","control-plane-kubeadm", "infrastructure-gcp"],
  "provider_repos": ["../cluster-api-provider-gcp"]
}
EOF
cmd/clusterctl/hack/local-overrides.py

git clone https://github.com/kubernetes-sigs/cluster-api-provider-gcp.git
git checkout origin/master

cat > ~/.cluster-api/clusterctl.yaml <<EOF
providers:
  - name: gcp
    url: /home/esudbat/.cluster-api/overrides/infrastructure-gcp/v0.3.0/infrastructure-components.yaml
    type: InfrastructureProvider
EOF

 export GCP_B64ENCODED_CREDENTIALS=$(cat capi-xxx.json  | base64 | tr -d '\n' )

$ clusterctl init --core cluster-api:v0.3.0 --bootstrap kubeadm:v0.3.0 --control-plane kubeadm:v0.3.0 --infrastructure gcp:v0.3.0
Fetching providers
Using Override="core-components.yaml" Provider="cluster-api" Version="v0.3.0"
Using Override="bootstrap-components.yaml" Provider="bootstrap-kubeadm" Version="v0.3.0"
Using Override="control-plane-components.yaml" Provider="control-plane-kubeadm" Version="v0.3.0"
Using Override="infrastructure-components.yaml" Provider="infrastructure-gcp" Version="v0.3.0"
Error: failed to read "metadata.yaml" from the repository for provider "infrastructure-gcp": failed to read file "/home/esudbat/.cluster-api/overrides/infrastructure-gcp/v0.3.0/metadata.yaml" from local release v0.3.0

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v1alpha3
- Minikube/KIND version: $ kind version
kind v0.8.1 go1.14.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04.4 LTS

**Comment by ncdc** [comment]
You need to create a metadata.yaml locally - see https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html for more details.

**Comment by sb1975** [comment]
created the metadata.yaml
$ cat .cluster-api/overrides/infrastructure-gcp/v0.3.0/metadata.yaml
apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
kind: Metadata
releaseSeries:
- major: 0
  minor: 3
  contract: v1alpha3
- major: 0
  minor: 2
  contract: v1alpha2
esudbat@capi-gcp:~$ clusterctl init --core cluster-api:v0.3.0 --bootstrap kubeadm:v0.3.0 --control-plane kubeadm:v0.3.0 --infrastructure gcp:v0.3.0
Fetching providers
...
Your management cluster has been initialized successfully!
You can now create your first workload cluster by running the following:
  clusterctl config cluster [name] --kubernetes-version [version] | kubectl apply -f -

Next Error : 
$ clusterctl config cluster capi-quickstart --kubernetes-version v1.17.3 --control-plane-machine-count=3 --worker-machine-count=3 --infrastructure gcp:v0.3.0 > capi-quickstart.yaml
Error: failed to read "cluster-template.yaml" from provider's repository "infrastructure-gcp": failed to read file "/home/esudbat/.cluster-api/overrides/infrastructure-gcp/v0.3.0/cluster-template.yaml" from local release v0.3.0

Copied the cluster-template.yaml 
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/master/templates/cluster-template.yaml

Another Error : 
 $ kubectl apply -f capi-quickstart.yaml
cluster.cluster.x-k8s.io/capi-quickstart created
gcpcluster.infrastructure.cluster.x-k8s.io/capi-quickstart created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capi-quickstart-control-plane created
machinedeployment.cluster.x-k8s.io/capi-quickstart-md-0 created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/capi-quickstart-md-0 created
Error from server (InternalError): error when creating "capi-quickstart.yaml": Internal error occurred: failed calling webhook "validation.gcpmachinetemplate.infrastructure.x-k8s.io": Post https://capg-webhook-service.capi-webhook-system.svc:443/validate-infrastructure-cluster-x-k8s-io-v1alpha3-gcpmachinetemplate?timeout=30s: dial tcp 10.99.231.88:443: connect: connection refused
Error from server (InternalError): error when creating "capi-quickstart.yaml": Internal error occurred: failed calling webhook "validation.gcpmachinetemplate.infrastructure.x-k8s.io": Post https://capg-webhook-service.capi-webhook-system.svc:443/validate-infrastructure-cluster-x-k8s-io-v1alpha3-gcpmachinetemplate?timeout=30s: dial tcp 10.99.231.88:443: connect: connection refused

capg-controller is in crashloopback
$ kubectl get all -A | grep webhook
capi-webhook-system                 pod/capg-controller-manager-65d9557887-qc29x                         1/2     CrashLoopBackOff   11         35m

$ kubectl get pods -A
NAMESPACE                           NAME                                                             READY   STATUS             RESTARTS   AGE
capg-system                         capg-controller-manager-7ffcdbd9c-sfzcl                          1/2     CrashLoopBackOff   15         53m
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-55674b574c-gf7hq       2/2     Running            0          53m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-7d9c974f48-cxb5w   2/2     Running            0          53m
capi-system                         capi-controller-manager-c555cd468-c5f9t                          2/2     Running            0          53m
capi-webhook-system                 capg-controller-manager-65d9557887-kg5zp                         1/2     CrashLoopBackOff   7          13m

**Comment by sb1975** [comment]
$ kubectl describe pod capg-controller-manager-7ffcdbd9c-sfzcl -n capg-system
Events:
  Type     Reason     Age                 From                               Message
  ----     ------     ----                ----                               -------
  Normal   Scheduled  55m                 default-scheduler                  Successfully assigned capg-system/capg-controller-manager-7ffcdbd9c-sfzcl to clusterapi-control-plane
  Normal   Started    55m                 kubelet, clusterapi-control-plane  Started container kube-rbac-proxy
  Normal   Pulled     55m                 kubelet, clusterapi-control-plane  Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1" already present on machine
  Normal   Created    55m                 kubelet, clusterapi-control-plane  Created container kube-rbac-proxy
  Warning  Unhealthy  55m                 kubelet, clusterapi-control-plane  Liveness probe failed: Get http://10.244.0.15:9440/healthz: dial tcp 10.244.0.15:9440: connect: connection refused
  Normal   Started    54m (x3 over 55m)   kubelet, clusterapi-control-plane  Started container manager
  Normal   Created    54m (x4 over 55m)   kubelet, clusterapi-control-plane  Created container manager
  Normal   Pulling    54m (x4 over 55m)   kubelet, clusterapi-control-plane  Pulling image "gcr.io/k8s-staging-cluster-api-gcp/cluster-api-gcp-controller:latest"
  Normal   Pulled     54m (x4 over 55m)   kubelet, clusterapi-control-plane  Successfully pulled image "gcr.io/k8s-staging-cluster-api-gcp/cluster-api-gcp-controller:latest"
  Warning  BackOff    4s (x265 over 54m)  kubelet, clusterapi-control-plane  Back-off restarting failed container

**Comment by sandhyashrek** [comment]
Same issue here.. Any fixes available?

**Comment by cloudcafetech** [comment]
I am getting following error ..

```
[root@kind cluster-api]# oc logs -f pod/capg-controller-manager-d489d98b4-l4mkx -n capg-system
error: a container name must be specified for pod capg-controller-manager-d489d98b4-l4mkx, choose one of: [manager kube-rbac-proxy]
[root@kind cluster-api]# oc logs -f pod/capg-controller-manager-d489d98b4-l4mkx -c manager -n capg-system
I0930 18:46:05.596236       1 listener.go:40] controller-runtime/metrics "level"=0 "msg"="metrics server is starting to listen"  "addr"="127.0.0.1:8080"
I0930 18:46:05.597244       1 controller.go:121] controller-runtime/controller "level"=0 "msg"="Starting EventSource"  "controller"="gcpmachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"zone":"","instanceType":""},"status":{"ready":false}}}
E0930 18:46:05.597371       1 source.go:88] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"GCPMachine\" in version \"infrastructure.cluster.x-k8s.io/v1alpha2\""  "kind"={"Group":"infrastructure.cluster.x-k8s.io","Kind":"GCPMachine"}
E0930 18:46:05.597416       1 main.go:145] setup "msg"="unable to create controller" "error"="no matches for kind \"GCPMachine\" in version \"infrastructure.cluster.x-k8s.io/v1alpha2\""  "controller"="GCPMachine"
```

**Comment by dlipovetsky** [comment]
This isn't the best place to ask for support. Please reach out on Kubernetes slack (#cluster-api)

/close
