### ISSUE TITLE
Allow for local-ssd

### ISSUE THREAD

**Issue by bdurrow** [kubernetes-sigs/cluster-api-provider-gcp#316]
[Also submitted in openshift/cluster-api-provider-gcp](https://github.com/openshift/cluster-api-provider-gcp/issues/124)
/kind feature

Given that in GCP local-ssds are very performant and with a 3 year commitment less expensive than pd-standard (I do not believe you can get commitment discounts on other storage) I would like to use them for my /var (and use a small pd-standard boot disk).  The fact that they are ephemeral and I can not shutdown machines where they are present is not a concern for kubernetes nodes.

Unfortunately, the cluster-api does not support them. When I create a machine config with a disk of type local-ssd I get the following error message (in openshift which shares the same limitations with a different implementation):
```
error launching instance: googleapi: Error 400: Invalid value for field 'resource.disks[1].type': 'PERSISTENT'. Cannot create local SSD as persistent disk., invalid
```
Here is the spec/providerSpec/disk[1] definition I used:
```
            - autoDelete: true
              image: blank
              sizeGb: 375
              type: local-ssd
```
When I look at the allowed [configuration values](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/11b95277f3121dc377412c589b3d6316ca6bef54/cloud/services/compute/instances.go#L80) I don't see any way to specify the type as required by the [google api](https://cloud.google.com/compute/docs/disks/local-ssd#api).

Additionally, I could not find a way to keep the `sourceImage` and 'sizeGB' from being specified or set the `interface`.

I am hesitant to work on a PR because I don't use Kubernetes directly but Openshift instead.  Even though this limitation exists in both implementations those implementations appear to be very different.  The relationship between the two is not clear.  It also isn't clear if I submit code to one project I would be able to submit a code based on the same work product to the other (based on licensing.  Because of this I don't have a good way to dogfood my change.

**Comment by dilyevsky** [comment]
@detiber I would like to claim this if nobody else has already.

**Comment by cpanato** [comment]
@dilyevsky go for it! 🎉 

/assign @dilyevsky 
/remove-help
