### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by bygui86** [kubernetes-sigs/cluster-api-provider-gcp#336]
Hi guys,

I started right couple of days ago with ClusterAPI and I like it a lot.

I work on GCP so I was trying to introduce ClusterAPI into my company, but I don't find any documentation about how to use properly ClusterAPI with GCP.

I found this for AWS: https://cluster-api-aws.sigs.k8s.io/

Is there anything similar for GCP?

**Describe the solution you'd like**

It would be very useful to have a documentation similar to ClusterAPI AWS provider (see https://cluster-api-aws.sigs.k8s.io/) like https://cluster-api-gcp.sigs.k8s.io/

/kind feature

**Comment by salasberryfin** [comment]
Docs are now available as a book at https://cluster-api-gcp.sigs.k8s.io/.

/close
