### ISSUE TITLE
avoid pull-cluster-api-provider-gcp-make-conformance from building images for every run

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cluster-api-provider-gcp#361]
search for `init_image` in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-gcp/360/pull-cluster-api-provider-gcp-make-conformance/1387800361498054656/build-log.txt

to see that this job `kubernetes-sigs_cluster-api-provider-gcp` has to build an image for every run as it is executed in a different gcp project every time. this adds to the time taken for the job.

It would be convenient if there is a common gcp-project that has a recent build of the image (and a separate job to refresh it!) instead so we can reduce the time taken for this job.

**Comment by dims** [comment]
cc @cpanato

**Comment by cpanato** [comment]
agree, this is in my backlog for some time, but I guess it is time to implement it :)

/assign

**Comment by cpanato** [comment]
we are building the image, but there are some permission issues, as soon this gets fixed we can get back to this issue

**Comment by cpanato** [comment]
this is done! :)
/close
