### ISSUE TITLE
Cannot create cluster using clusterctl: unable to create master machine: timed out waiting for the condition

### ISSUE THREAD

**Issue by oxddr** [kubernetes-sigs/cluster-api-provider-gcp#38]
I am unable to create cluster with clusterctl using this repo from HEAD. I am getting:
F0928 10:27:27.798129  159895 create_cluster.go:61] unable to create master machine: timed out waiting for the condition

Increasing logging level to 5 doesn't provide much more information, I see a lot of checks:
I0928 10:19:06.558359  159895 clusterclient.go:433] Waiting for Machine gce-master-4btlq to become ready...                                                                                                                                                                               

There is no trace on GCE side of any attempts to create a VM (not operations logged etc.).

**Comment by oxddr** [comment]
Actual cause: https://github.com/kubernetes-sigs/cluster-api/issues/475

I am about to update the documentation, so it's clear which version of minikube should be used until the issue is fixed.

**Comment by roberthbailey** [comment]
Thanks for noticing, finding the cause, and sending a fix. This has been a "known issue" without a simple documentation fix for a while now.
