### ISSUE TITLE
Multiple links in `README.md` are broken.

### ISSUE THREAD

**Issue by jayesh-srivastava** [kubernetes-sigs/cluster-api-provider-gcp#424]
/kind bug
/kind documentation

**What steps did you take and what happened:**
Multiple links are broken in the `README.md` file. You'll have to check one by one and attach the link of the mentioned file wherever necessary.

**What did you expect to happen:**
The links should direct to the mentioned page.

**Comment by harshmathurx** [comment]
I'd like to give it a try
