### ISSUE TITLE
🏃extend ci-conformance.sh testing capability

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#428]
/kind feature

Extending ci-conformance.sh testing capability to allow other tests to be run on a CAPZ cluster - a temporary solution until kubernetes-sigs/cluster-api#2826 is fixed.

**Describe the solution you'd like**

[A clear and concise description of what you want to happen.]
`ci-entrypoint.sh` will be the new entrypoint for all E2E tests. It can accept k/k master branch or release branches, and has the option to run upstream E2E tests or bring your own E2E tests by appending custom commands to `./scripts/ci-entrypoint.sh.`

**Anything else you would like to add:**

Refer to: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/617
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/scripts/ci-entrypoint.sh
As of now try adding the `scripts/ci-entrypoint.sh` file, and as we move forward we could see for the rest.

**Comment by MadhavJivrajani** [comment]
@sayantani11 please ensure that the issue contains sufficient context and information about what exactly needs to be done so that a new contributor can pick it up with almost 0 barrier to entry. As mentioned by the bot, the guidelines for good-first-issues can be found [here](https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md#good-first-issue). 

/remove-good-first-issue
Please feel free to re-apply once sufficient information has been added.

**Comment by Darshnadas** [comment]
Can I take this issue?

**Comment by sayantani11** [comment]
@Darshnadas You will see a PR reference we are looking for something similar, but as of now our main focus will be the `ci-entrypoint.sh` file. I have attached the reference to the file with latest update. This script is present in CAPZ and we are wanting the same for CAPG. For the variables in the script, you might try having a look at https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/docs/book/src/topics/prerequisites.md#setup-environment-variables. For the ensure scripts try looking at the hack folder. And for any problems, we can start a thread in Slack if you want.

**Comment by PranshuSrivastava** [comment]
Can i also work on this issue?

**Comment by Darshnadas** [comment]
@sayantani11 Sure, a thread starting in a slack sounds good

**Comment by sayantani11** [comment]
@PranshuSrivastava as you can see @Darshnadas has claimed the issue, so I think one person will be okay for the PR. You can still browse through the project and see if there are other changes that you could introduce for enhancement of the project. Hope you understand🙂
/unassign @PranshuSrivastava

**Comment by PranshuSrivastava** [comment]
@sayantani11 Sure, no problem!

**Comment by mehabhalodiya** [comment]
@sayantani I would like to work on this if nobody else is doing so.

**Comment by sayantani11** [comment]
@mehabhalodiya There's a PR but guess that needs improvement, you can still work on it

**Comment by mehabhalodiya** [comment]
@Darshnadas I see you are working on this. Let me know if you wouldn't, I can continue 🙂
