### ISSUE TITLE
Update kubernetes to latest version

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#460]
/kind feature

**Describe the solution you'd like**
As we know the last release version of Kubernetes happens to be 1.22, but the project is still set up based on version 1.20.9. So we need to update it in the files:
`hack/ci/e2e-conformance.sh`
`scripts/ci-e2e.sh`

```sh
export KUBERNETES_MAJOR_VERSION="1"
export KUBERNETES_MINOR_VERSION="22"
export KUBERNETES_PATCH_VERSION="0"
```

**Comment by robotjellyzone** [comment]
Looking out for a similar good first issue, thanks for posting!!

**Comment by cpanato** [comment]
it is not only updating this the capg project. we also need to build those images

made a PR to update the images to the latest https://github.com/kubernetes-sigs/image-builder/pull/733 and after that, we can check if the images are available and then update the jobs here and in the test-infra repo

**Comment by robotjellyzone** [comment]
oh ok @cpanato  actually I don't have much idea about building images and thats why took this **good first issue** but if you can help me to learn about it then I can definitely try to build those images as well :)

**Comment by sayantani11** [comment]
@cpanato Can I make the PR in test-infra?

**Comment by cpanato** [comment]
@sayantani11 sure, need to update the conformance test to match the k8s version that we will use https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-gcp/cluster-api-provider-gcp-presubmits.yaml#L193

but also need to wait for https://prow.k8s.io/?job=periodic-image-builder-gcp-all-nightly for the next run today to build the new images and then update the k8s version and image name in the PR above.

you can open the pr in test infra but we need to wait the images/update in capg PR
