### ISSUE TITLE
Update k8s.sigs.io/cluster-api source to upstream

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-gcp#48]
The source changed as part of #37. Now that upstream has migrated to CRDs, the source can changed back. 

https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/c6fbd195510994139762a989c56057125d5358ca/Gopkg.lock#L800

**Comment by roberthbailey** [comment]
This has been fixed.
