### ISSUE TITLE
Update the support policy according to new release

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#485]
/kind documentation 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
As we have seen, we have made some changes for our v1beta1 release, and those changes should reflect on our support policy section in our `Readme.md`
The table needs to be updated for better understanding of the compatibility of the release and that of K8s.

|  | Cluster API `v1alpha3` (`v0.3.x`) | Cluster API `v1alpha4` (`v0.4.x`) | Cluster API `v1beta1` (`v1.0.x`) |
|---|---|---|---|
|Google Cloud Provider `v0.3.x` | ✓ |  |  |
|Google Cloud Provider `v0.4.x` |  | ✓ |  |
|Google Cloud Provider `v1.0.x` |  |  | ✓ |

This provider's versions are able to install and manage the following versions of Kubernetes:

|  | Google Cloud Provider `v0.3.x` | Google Cloud Provider `v0.4.x` | Google Cloud Provider `v1.0.x` |
|---|:---:|:---:|:---:|
| Kubernetes 1.15 |  |  |  |
| Kubernetes 1.16 | ✓ |  |  |
| Kubernetes 1.17 | ✓ | ✓ ||  |
| Kubernetes 1.18 | ✓ | ✓ | ✓ |
| Kubernetes 1.19 | ✓ | ✓ | ✓ |
| Kubernetes 1.20 | ✓ | ✓ | ✓ |
| Kubernetes 1.21 |  | ✓ | ✓ |
| Kubernetes 1.22 |  |  | ✓ |

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ShivamTyagi12345** [comment]
Would like to help
/assign
:)

**Comment by sayantani11** [comment]
@ShivamTyagi12345 Updates?

**Comment by ShivamTyagi12345** [comment]
> @ShivamTyagi12345 Updates?

Will make my PR by this Sunday:)

**Comment by mehabhalodiya** [comment]
I have submitted a PR as I don't see any updates 🙂 
Thanks!
