### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by jayesh-srivastava** [kubernetes-sigs/cluster-api-provider-gcp#487]
There's a small typo at `line 65` in the `README.md` file with the correct word being `environment`. Also at `line 68`, `this` should be replaced with `these`. Contributors should also look for other possible typos and try to correct them as well.

**Comment by jayesh-srivastava** [comment]
@Kishy1224 Really sorry but @wondersumanth assigned it first and this issue doesn't require two contributors. Maybe you can try next time because there are always new good-first-issues coming up. Hope you understand. Un-assigning you now.

**Comment by wondersumanth** [comment]
@KelvinEuclides I m looking into this. could you please unassign yourself

**Comment by jayesh-srivastava** [comment]
@KelvinEuclides Really sorry but @wondersumanth assigned it first and this issue doesn't require two contributors. Maybe you can try next time because there are always new good-first-issues coming up. Hope you understand. Un-assigning you now.

**Comment by KelvinEuclides** [comment]
Sorry
