### ISSUE TITLE
Sorting the CAPG documentation into a book

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#490]
/kind feature

There are still a few improvements needed in CAPG documentation, but at this moment we can still work on the book. This will be something similar to: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/858
It will be better for new contributors or will provide easier usage to the users, apart from this it will also help in better management of docs.

We can have the CAPG docs hosted on Netlify site and request for a new site from the K8s org. 
We can iterate over the content of the book later, but for now can just set up the site with the existing topics.

**Note:** Only people with owner rights in a repository can deploy on a Netlify site.

**Comment by sayantani11** [comment]
@cpanato @dims

**Comment by sayantani11** [comment]
Requested in #336 as well
/priority important-soon

**Comment by salasberryfin** [comment]
Thanks @richardcase. I'll be working on this.

**Comment by salasberryfin** [comment]
As discussed in this week's community meeting, we'll be working on creating a basic structure of topics for the book and then expanding the contents. We can use other CAPI providers as reference for the must-have topics. Further related issues are expected to emerge as a consequence of this so we can use this one to centralize most of the discussion.

**Comment by cpanato** [comment]
that sounds awesome! thanks for working on this

**Comment by salasberryfin** [comment]
The following tasks are required to have the book published:
- [ ] Create netlify configuration: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1131
- [ ] Request site and project subdomain.
- [ ] Sort docs into book.
