### ISSUE TITLE
Replace hack/ensure-*.sh scripts with `go install`

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#491]
/kind feature

**Describe the solution you'd like**
In the `./hack` directory are scripts named `ensure-<something>.sh.` Some of these install Go-based tools, and they could perhaps be replaced entirely by invocations of `go install`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mehabhalodiya** [comment]
@sayantani11 I would like to work on this. May I know what changes need to be done in the scripts named `ensure-<something>.sh`?

**Comment by sayantani11** [comment]
Yes @mehabhalodiya the changes will be something similar to the one done in this PR: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/497 
The goal would be to use the Makefile approach that installs all the tools into the `hack/tools/bin` folder and have the scripts use these tools. For any further issues we can have a thread in slack.

**Comment by sayantani11** [comment]
@mehabhalodiya Any progress with it?
