### ISSUE TITLE
golangci-lint should be in parity with CAPI

### ISSUE THREAD

**Issue by jayesh-srivastava** [kubernetes-sigs/cluster-api-provider-gcp#496]
/kind feature

**Describe the solution you'd like**
There are some linters that are present in CAPI but not in CAPG. We could add those missing linters in CAPG too to make the contributor experience more similar.

**Anything else you would like to add:**
Missing linters in CAPG:
- containedctx 
- gci
- noctx
- predeclared
- thelper
- unused

**Comment by jayesh-srivastava** [comment]
If this makes sense, can we have one PR per linter?
cc @cpanato @dims

**Comment by cpanato** [comment]
@jayesh-srivastava one pr for all is enough
