### ISSUE TITLE
Improvement in Readme 

### ISSUE THREAD

**Issue by Anubhavdevv** [kubernetes-sigs/cluster-api-provider-gcp#509]
/kind feature

**Describe the solution you'd like**

[Readme is not looking good Pictures in starting are not properly aligned there is no space in between them and there must be heading at the top before image which describe the repository about.]

**Anything else you would like to add:**

[In some places there is not proper alignment and I can improve that]

**I would like to work on this issue Please assign this issue to me** 

/assign

**Comment by sayantani11** [comment]
@Anubhavdevv Any updates on the PR?

**Comment by Anubhavdevv** [comment]
Yes working on it. I will make the pr by Tomorrow

**Comment by Anubhavdevv** [comment]
@sayantani11 Please Review it

**Comment by cpanato** [comment]
there is no issue wit the images in the readme at this moment 
closing this issue
