### ISSUE TITLE
Verify targets should be made in parity with CAPI

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#510]
/kind bug

**What steps did you take and what happened:**
Did a comparison of verify targets used in core capi vs capg found out that couple of verify targets are missing in capg. If it makes sense, we can add those to CAPG in order to make the contributor experience more similar. This should also help improve the developer experience. 
The following section has the comparison matrix.

Missing targets is CAPG but present in CAPI:
- lint-fix
- apidiff
- verify-conversions
- verify-tiltfile
- verify-book-links
We can discuss about this, and if accepted we can add this targets too.

**Comparison matrix**
Validations executed via make

| S.no | make target | CAPI | CAPG | Function |
| --- | --- | --- | --- | --- |
| 1. |  lint-fix | ✔️ |  ❌ | runs golangci-lint with --fix |
| 2. |  apidiff | ✔️ |  ❌ | diffs API changes on PRs |
| 3. |  verify | ✔️ | ✔️ | target which runs all the other verify targets |
| 4.|  verify-modules | ✔️ | ✔️ | verifies go.mod’s are up-to-date |
| 5. |  verify-gen | ✔️ |  ✔️ | verifies all generated files are up-to-date |
| 6. |  verify-conversions | ✔️ |  ❌ | verifies all API types implement conversions |
| 7. |  verify-boilerplate | ✔️ |  ✔️ | verifies file headers |
| 8. |  verify-shellcheck | ✔️ |  ✔️ | verifies shell scripts |
| 9. |  verify-tiltfile | ✔️ |  ❌ | verifies tiltfile |
| 10. |  verify-booklinks | ✔️ |  ❌ | verifies links in books |

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sayantani11** [comment]
cc @cpanato 
/assign

**Comment by sayantani11** [comment]
Have previously added the shellcheck script so we have done one part

**Comment by cpanato** [comment]
sounds good

**Comment by jayesh-srivastava** [comment]
@sayantani11 If it's okay with you, I can make some PRs too. Was working on the verify-conversions so that one and the apidiff too. Maybe you can review them. What say?

**Comment by sayantani11** [comment]
@jayesh-srivastava I am doing good!!! I thought of doing the smaller changes in one, and the scripts will be done separately. I will surely reach out for help if required, Thanks!

**Comment by sayantani11** [comment]
As for CAPG still hasn't introduced a book, so at this moment we don't need `verify-booklinks`
