### ISSUE TITLE
Upgrade the versions of tools in CAPG

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#511]
/kind feature

**Describe the solution you'd like**

CAPG still uses older versions of controller-runtime, K8s-client, controller-tools and Kustomize. It will be better if we can upgrade it to the latest version, to avoid any future inconvenience, and to be in parity with CAPI & other CAP providers.
- upgrade controller-runtime to 0.11.0
- upgrade K8s-client to 1.23
- upgrade controller-tools 0.8.0
- upgrade Kustomize to v4.4.0

**Comment by jayesh-srivastava** [comment]
@sayantani11 Will wait for [kubernetes-sigs/cluster-api-provider-gcp/pull/501](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/501) to get merged to ensure no conflicts.
