### ISSUE TITLE
Add a README about Flavors

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#555]
/kind documentation

Currently CAPG doesn't have any readme about flavors. It will be great if we could add one for a better developer experience.

**Comment by hackeramitkumar** [comment]
@richardcase @cpanato I would like to work on it. Can you provide me with any reference from where I can take help?

**Comment by hackeramitkumar** [comment]
@richardcase where can I find all the CAPG flavours?? I have seen in CAPZ there are templates for flavours.
Did we not written templates for the flavours?? 
Please give me some idea about it.

**Comment by hackeramitkumar** [comment]
@sayantani11 any idea??
