### ISSUE TITLE
ClusterClass support

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-gcp#561]
/kind feature

CAPI introduced a ClusterClass, an experimental feature  https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/index.html, which will be used to provide easy stamping of clusters of similar shapes and improve UX.

This issue is tracking the list of tasks that should be implemented to support ClusterClass for GCP. 

Tasks
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/397
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/558
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/560

**Comment by mehabhalodiya** [comment]
@pydctw I think we should close this as I see the listed tasks have been addressed.

**Comment by pydctw** [comment]
> @pydctw I think we should close this as I see the listed tasks have been addressed.

Adding a documentation is still on my to-do list.
