### ISSUE TITLE
Pick a zone for worker nodes automatically when a failureDomain is not specified in MachineDeployment

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-gcp#569]
/kind feature

This is a feature request and also a bug report for a specific case.

**Describe the solution you'd like**
CAPG should pick a zone for worker nodes automatically when a failureDomain is not specified in MachineDeployment.

**Anything else you would like to add:**
While creating a cluster, the following error occurred.
```
E0323 16:50:27.518202       9 reconcile.go:123] controller/gcpmachine "msg"="Error looking for instnace" "error"="googleapi: Error 400: Invalid value for field 'zone': ''. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalid" "namespace"="gcp" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="GCPMachine" "name"="my-gcp-cluster-md-0-jczcj" "zone"=""
E0323 16:50:27.518238       9 gcpmachine_controller.go:229] controller/gcpmachine "msg"="Error reconciling instance resources" "error"="googleapi: Error 400: Invalid value for field 'zone': ''. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalid" "name"="my-gcp-cluster-md-0-jczcj" "namespace"="gcp" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="GCPMachine"
```

This happens because zone info for an instance spec is derived from machine's `spec.FailureDomain`. See [code](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/d367749cf8752e925a3b2d74159776b95327ce15/cloud/scope/machine.go#L94). It works for control planes but requires failureDomain to be specified in MachineDeployment, otherwise the above error occurs. 

This behavior is different from other providers. Compare the following cluster templates. CAPG is the only one that requires failureDomain field in MachineDeployment spec to function properly.
* CAPG: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/templates/cluster-template.yaml#L72-L94
* CAPA: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/templates/cluster-template.yaml#L69-L90
* CAPZ: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/cluster-template.yaml#L150-L172

**How to Reproduce the Issue**
Remove failureDomain from MachineDeployment spec in the [template](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/templates/cluster-template.yaml#L84) and create a cluster.

**Comment by aniruddha2000** [comment]
Hello @pydctw, I would like to work on the issue 😄

**Comment by aniruddha2000** [comment]
What is the difference between [ClusterScope](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/cloud/scope/cluster.go#L77) Struct and [MachineScope](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/cloud/scope/machine.go#L78) Struct? Does the `ClusterScope` is the management cluster/Control Plane specification?

There is a function called [SetFailureDomains](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/cloud/scope/cluster.go#L150) which is running upon the ClusterScope struct. Then, Should I implement another  SetFailureDomains function upon the MachineScope struct and will check the if there is a failure zone or not if not it will set one.

**Comment by aniruddha2000** [comment]
I think for the aws the `availabilityZone` is equivalent to the GCP `failureDomain`. And here in the aws [SetProviderID](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7a545cd1aa5d05e5a0364a49b3c700341737ca61/pkg/cloud/scope/machine.go#L145) is working upon the `MachineScope` to set the availibility zone. Can we take something approach like this?

**Comment by aniruddha2000** [comment]
I think [here](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/421b2395a8c02e0f73be84e91e283193c3e718fd/controllers/gcpcluster_controller.go#L169-L196) the `failureDomain` is getting set in the control plane right?

So can I make a something similar in the [reconcile function](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/421b2395a8c02e0f73be84e91e283193c3e718fd/controllers/gcpmachine_controller.go#L219) of the `GCPMachineReconciler` struct and get the regions and zones and set the failure domain bool for the machine deployment and set the failure domain like [this](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/421b2395a8c02e0f73be84e91e283193c3e718fd/controllers/gcpcluster_controller.go#L196)?

**Comment by pydctw** [comment]
Before I gives my thoughts, feel free to explore with your ideas because there can be multiple approaches to solve this issue.

Currently, instance spec gets a zone from Machine spec's failureDomain field: [code](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/568764a89f85298cda07bec15c774f83aed2715c/cloud/scope/machine.go#L311)

```go
func (m *MachineScope) Zone() string {
	if m.Machine.Spec.FailureDomain == nil {
		return ""
	}

	return *m.Machine.Spec.FailureDomain
}
```

The `Machine.Spec.FailureDomain` comes from MachineDeployment's FailureDomain. What I described in the issue is that CAPG should be able to pick a zone even if MachineDeployment's FailureDomain is not set.

As you have observed, [zones info](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/421b2395a8c02e0f73be84e91e283193c3e718fd/controllers/gcpcluster_controller.go#L169-L196) is already available in Cluster, given a region.
```go
zones, err := clusterScope.Cloud().Zones().List(ctx, filter.Regexp("region", region.SelfLink))
```

You could probably pick a zone from this list if Zone() returns "".

**Comment by pydctw** [comment]
> So can I make a something similar in the [reconcile function](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/421b2395a8c02e0f73be84e91e283193c3e718fd/controllers/gcpmachine_controller.go#L219) of the `GCPMachineReconciler` struct and get the regions and zones and set the failure domain bool for the machine deployment and set the failure domain like [this](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/421b2395a8c02e0f73be84e91e283193c3e718fd/controllers/gcpcluster_controller.go#L196)?

We don't want to update MachineDeployment failure domain if it is not already set.

**Comment by pydctw** [comment]
> I think for the aws the `availabilityZone` is equivalent to the GCP `failureDomain`. And here in the aws [SetProviderID](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7a545cd1aa5d05e5a0364a49b3c700341737ca61/pkg/cloud/scope/machine.go#L145) is working upon the `MachineScope` to set the availibility zone. Can we take something approach like this?

`SetProviderID` sets a provider ID after an instance is created using an Info returned from AWS. As we want to set a zone to create an instance, it is not related.
