### ISSUE TITLE
Update meeting information in the README.md

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#579]
/kind documentation

As we know, that CAPG has started it's own monthly meeting. To make things easier for new contributors, we should update our meeting details in the readme file.
The information about the meeting can be found here:
https://github.com/kubernetes/community/pull/6582/files#diff-0dfeafbc725d0fb70c96aea3dfbc5b90d4402266da37eedde85b032aaf117049R127-R130

**Comment by sayantani11** [comment]
/good-first-issue
The PR can be merged after the zoom link is decided

**Comment by cpanato** [comment]
this can be just a link to the community page to avoid much changes

**Comment by ibnjunaid** [comment]
@sayantani11 is the zoom link decided? If yes can you please give it to me?

**Comment by NitishKumar06** [comment]
Hi @ibnjunaid Are you working on this issue?
