### ISSUE TITLE
Enable apidiff to report only actual API changes 

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-gcp#592]
/kind bug

**What steps did you take and what happened:**
Recently added apidiff reports any changes in exposed field/function as breaking changes. 

As an example, one of recent [PR test](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-gcp/587/pull-cluster-api-provider-gcp-apidiff/1518554081407275008) fails with the following output, which doesn't have any API changes.
```bash
*** Running go-apidiff ***
sigs.k8s.io/cluster-api-provider-gcp/cloud/services/compute/instances
  Incompatible changes:
  - MachineGetter.Project: added
sigs.k8s.io/cluster-api-provider-gcp/cloud
  Incompatible changes:
  - MachineGetter.Project: added
sigs.k8s.io/cluster-api-provider-gcp/cloud/scope
  Compatible changes:
  - (*MachineScope).Project: added
...
```

**What did you expect to happen:**
apidiff should only inform about API changes within `api/` directory

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ShivamTyagi12345** [comment]
I have been doing NonCode Contributions so far at Kubernetes for over a year now skipping a few months while being regular over the others. Now I would like to do consistent code contributions. 

It may take me longer than other contributors but I would like to solve this issue.I would really appreciate an initial help on getting started

/assign

**Comment by Prajyot-Parab** [comment]
@ShivamTyagi12345 Please let me know if you are still working on this one. If not, I will pick it up.

**Comment by ShivamTyagi12345** [comment]
Go ahead
