### ISSUE TITLE
Automatically create firewall rules for networks

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-gcp#593]
/kind feature

**Describe the solution you'd like**
Currently, a user needs to create and delete firewall rules manually if they want to use a network other than `default` one. CAPG should automate this and create firewall rules for networks created by CAPG.

Also, firewall rules should allow only necessary traffic flow and restrict source/destinations, meaning current firewall rules need to be refined ->  It may not require a full design doc but research and discussion w/community will be needed before full implementation.

**Anything else you would like to add:**
Where firewall rules are created manually for e2e tests: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/scripts/ci-e2e.sh#L108-L116

**Comment by pydctw** [comment]
cc @lubronzhan

**Comment by sayantani11** [comment]
So I was thinking do we add another condition or modify the existing?

**Comment by pydctw** [comment]
> So I was thinking do we add another condition or modify the existing?

We will need to delete some existing rules and add more rules to define more granular rules. For example, firewall rules for control plane and worker nodes should be different.

**Comment by SubhasmitaSw** [comment]
I'd like to work on this, @pydctw is this still up for assignment?

**Comment by sayantani11** [comment]
@SubhasmitaSw guess it is

**Comment by pydctw** [comment]
@SubhasmitaSw, this is a much needed feature. Go for it.

**Comment by SubhasmitaSw** [comment]
I may be a bit slow to respond, but I'm working on it! 

/assign

**Comment by gustavomfc** [comment]
@SubhasmitaSw are you still working in it? Can I help you with anything?
