### ISSUE TITLE
Document the exact IAM permissions needed on the GSA used by CAPG

### ISSUE THREAD

**Issue by itspngu** [kubernetes-sigs/cluster-api-provider-gcp#629]
/kind documentation

The Quickstart/Prerequisite docs at https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/docs/book/src/topics/prerequisites.md#create-a-service-account ask the user to

> [...] create a new service account with Editor permissions. Afterwards, generate a JSON Key and store it somewhere safe.

Assigning such a broad aggregated IAM role to a service account is problematic from a security perspective. The exact permissions the GSA needs should be documented, and ideally any e2e tests would include running the controller with the documented/defined least privileges required.

Furthermore, I personally think the linked doc should be updated reminding users that generating and downloading a JSON key for a GSA is a quick/easy way to get started with CAPG, but a more secure means to grant the controller access to GCP APIs should be used in a production setup.

**Comment by sayantani11** [comment]
@itspngu Any updates?

**Comment by sayantani11** [comment]
related to #451

**Comment by itspngu** [comment]
> @itspngu Any updates?

Hey, haven't had the chance to work on this yet sadly because I'm blocked internally. Feel free to re-assign if it's urgent and somebody else wants to work on this issue, else I will report back with my findings once I had the opportunity to iron things out.

**Comment by sayantani11** [comment]
Yeah sure! Take your time. I was just checking in, nothing urgent.
