### ISSUE TITLE
Enable Feature Gates

### ISSUE THREAD

**Issue by evanfreed** [kubernetes-sigs/cluster-api-provider-gcp#643]
/kind feature

**Describe the solution you'd like**
Other providers support feature gates (ex. [AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/main/feature) and [Azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/feature)).  It'd be good to align this wiring with the other CSPs.  This will be needed to support additional functionality and features in the future.

**Comment by richardcase** [comment]
This will be needed for #297, as machine pools are still experimental.
