### ISSUE TITLE
Add codespell to CI

### ISSUE THREAD

**Issue by evanfreed** [kubernetes-sigs/cluster-api-provider-gcp#681]
/kind feature

**Describe the solution you'd like**
To limit the number of spelling issues, it'd be nice to incorporate https://github.com/codespell-project/codespell.

**Comment by cpanato** [comment]
the other CAPx are using this as well?

**Comment by evanfreed** [comment]
Azure [does](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/.github/workflows/codespell.yml) but it doesn't look like AWS does.  Seems to be more independently decided.  This is more suggestion to keep things clean and consistent, I'm fine either way.
