### ISSUE TITLE
Simplify and reuse variables in `hack/tools/*.sh` scripts

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#698]
/kind feature

**Describe the solution you'd like**
We have a few variables in CAPG that are being reused in every script. A good addition will be if we introduce a new script called `common_vars.sh` which will have all the common variables like `KUBECTL`, `KIND`, `KUSTOMIZE` , which will be referenced in the `hack/tools*.sh` scripts. This will simplify and reuse of the variables. I have seen this issue being raised in CAPZ and I feel this will be a great addition to CAPG as well.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by viveksahu26** [comment]
Hey @sayantani11 , I am really willing to work on this issue.
/assign

**Comment by harshitasao** [comment]
Hi @sayantani11. Since there hasn't been any progress on this issue in a long time, I'd like to take it up.

/assign

**Comment by Chinwendu20** [comment]
Please is this issue still relevant? I saw that the last PR last linked to it was closed.

 I actually went on to look for the script in hack/tools directory. I found some scripts in hack/ directory could those be the scripts that you are referring to?

Should this is

**Comment by richardcase** [comment]
Based on the comment in #749 :

/close
