### ISSUE TITLE
Feature request: list default available failure domains for CAPG cluster

### ISSUE THREAD

**Issue by faiq** [kubernetes-sigs/cluster-api-provider-gcp#708]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

As a cluster administrator, I'd like a list of available failure domains for the GCP Cluster I have created and for that to be reflected in the cluster status. 

Other Cluster API provider such as CAPA and CAPZ provide this functionality see:

- [CAPZ status](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/afc2ca0b9ab620a409e00b606b49b85bbf04beb9/api/v1alpha4/azurecluster_types.go#L90)
- [CAPA status](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/818abca14a8b61f1d55eb13a6b3b7ca37fb6396b/api/v1beta1/awscluster_types.go#L203)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by basit9958** [comment]
@faiq this feature has already been implemented 
check : https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/cb254f8edb5295e9e7717514e0b13c5e9a4a58c2/cloud/scope/cluster.go#L144

**Comment by SubhasmitaSw** [comment]
Since this feature has already been implemented, closing this. Feel free to reopen if there's any additional context to be added. 

/close
