### ISSUE TITLE
Consider changing API group

### ISSUE THREAD

**Issue by justinsb** [kubernetes-sigs/cluster-api-provider-gcp#75]
Our API group for config objects is `gceproviderconfig.k8s.io`, and the kind is `GCEClusterProviderSpec`

I'm wondering if we should try to have something to do with cluster api in there, and try to be less specific about config.

e.g. cluster-api is `cluster.k8s.io` - should we be `gce.cluster.k8s.io` ?

(extracted for focused bikeshedding from https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/58/files#r239503537 )

**Comment by roberthbailey** [comment]
If we are going to change the api group, the sooner the better. Want to send a PR?
