### ISSUE TITLE
Invalid equality prevents the usage of local-ssd disks

### ISSUE THREAD

**Issue by silenteh** [kubernetes-sigs/cluster-api-provider-gcp#768]
/kind bug

While trying to use local-ssd disks I came across the following error:

```bash
Error 400: Invalid value for field 'resource.disks[1].type
Cannot create local SSD as persistent disk
```

After further inspection of the source code it turns out that the following equality can never be satisfied.

https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/26add93f103a6ca8ca9fb9f26873cd5a51d64cf4/cloud/scope/machine.go#L257

I have a fix ready for it, however, before I open a pull request I have a question about unit tests.  
This seems to be a case where having unit tests could catch these classes of bugs.  
In my fix I did provide a unit test to validate that the fix is correct but, it seems, you are preventing to push any `_test.go` files, via`.gitignore`

Is this done on purpose ?

**Comment by silenteh** [comment]
Ping

**Comment by cpanato** [comment]
i dont see a rule that blocks `_test.go` files to be added in the `.gitignore`

but feel free to open a PR :) thanks for the report
