### ISSUE TITLE
Support for prebuilt Cluster API capable images.

### ISSUE THREAD

**Issue by RyuSA** [kubernetes-sigs/cluster-api-provider-gcp#806]
/kind feature

**Describe the solution you'd like**
To go through getting started of Cluster API with GCP, users is required to build a custom image for each project. I think this will confuse them.
![image](https://user-images.githubusercontent.com/12961775/212706131-dc858fd5-7cc6-4377-b23b-93d6f8afbf47.png)
https://cluster-api.sigs.k8s.io/user/quick-start.html#required-configuration-for-common-providers

Also, for many users, a custom image is too much and not necessary at first. And simply configuring custom resources, such as `KubeadmConfig`, should be sufficient.

Why not provide a prebuilt custom image and can easily be getting started, like AWS and Azure?

**Anything else you would like to add:**
I'm not sure if this repo is good place to issue this idea. If I need to move this issue, I'll do that.

**Comment by cpanato** [comment]
thanks!
are you willing to help on this and test this approach and maybe add a test in our CI?

**Comment by RyuSA** [comment]
@cpanato Sure, I'd like to contribute this feature. But before starting implementation, we need to decide below. 

- Which gcp project does `cluster-api-provider-gcp` can use?
  - custom image storage incurs costs. https://cloud.google.com/compute/all-pricing#imagestorage
- Image versioning?
  - we can list all pairs of kubernetes version and Ubuntu version(1.25.5*18.04, 1.25.5*20.04, 1.25.4*18.04, 1.25.4*20.04, ...)
  - do everything?

**Comment by cpanato** [comment]
I'm sorry now I understand the issue, I had another understanding. sorry

We already prebuilt the images to use in our CI (https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi/packer/gce/ci/nightly) and the job https://testgrid.k8s.io/sig-cluster-lifecycle-image-builder#periodic-image-builder-gcp-all-nightly

**Comment by Chinwendu20** [comment]
I guess we can close this issue now

**Comment by cpanato** [comment]
sounds good

**Comment by cpanato** [comment]
will close this for now
