### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by damdo** [kubernetes-sigs/cluster-api-provider-gcp#843]
/kind feature

**Describe the solution you'd like**
I was wondering if there are any plans in regards to releasing a newer minor or patch release to cover [the bump in k8s dependencies](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/da5be4adc37edadf2a0bab84e2da58325aa12cb4/go.mod#L24-L27), the use of [cluster-api v1.3](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/766) and in general some vulnerable dependencies that have [already been bumped on main](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/da5be4adc37edadf2a0bab84e2da58325aa12cb4/go.mod#L21) but are not yet present in a release. 

Thanks!

cc. @richardcase @cpanato @dims

**Comment by cpanato** [comment]
thanks for the issue, yes, planning a 1.3 release, but I need to check a few things, but lets plan that to be released in two weeks from now

/assign

**Comment by hackeramitkumar** [comment]
@cpanato @richardcase Do we have release team for it??

**Comment by cpanato** [comment]
@hackeramitkumar i dont think we need one, we release in cycles and the release process is pretty fast

**Comment by hackeramitkumar** [comment]
Do we have any release tasks  tracking docs??

**Comment by damdo** [comment]
Thanks @cpanato

**Comment by damdo** [comment]
Looks like `v1.3.0` is out now.
Thanks a lot for this @cpanato, closing this issue now.
