### ISSUE TITLE
Unable to set instanceType for managed GKE Cluster

### ISSUE THREAD

**Issue by bubbaksmith** [kubernetes-sigs/cluster-api-provider-gcp#897]
/kind bug

**What steps did you take and what happened:**
There is no evident place to specify machine/instance-type for nodepools. This could be a lack of information/misunderstanding on my part, but I can see others hitting this same roadblock.

I can see this also being a request/feature as opposed to bug, if it's documentation/context that I am missing. 
 
```bash
kind create cluster -n local

export EXP_CAPG_GKE=true
export EXP_MACHINE_POOL=true
clusterctl init --infrastructure gcp

# CRDs used in GKE flavor quickstart cluster
export CRDS="gcpmanagedclusters.infrastructure.cluster.x-k8s.io gcpmanagedcontrolplanes.infrastructure.cluster.x-k8s.io gcpmanagedmachinepools.infrastructure.cluster.x-k8s.io machinepools.cluster.x-k8s.io clusters.cluster.x-k8s.io"

for crd in $CRDS; do 
  kubectl get $crd -o yaml | egrep -i "(instance|machine)-?(type)?" | grep -v "apiVersion" # dont include last-applied-configuration in results
done
  kind: GCPManagedMachinePool
    - gcpmanagedmachinepool.infrastructure.cluster.x-k8s.io
      kind: MachinePool
      reason: GKEMachinePoolCreated
      type: GKEMachinePoolCreating
      type: GKEMachinePoolReady
      reason: GKEMachinePoolUpdated
      type: GKEMachinePoolUpdating
  kind: MachinePool
    - machinepool.cluster.x-k8s.io
          kind: GCPManagedMachinePool
```

Previously used environment variables dont seem to work either.
```bash
$ GCP_B64ENCODED_CREDENTIALS=$(cat /Users/bubba/dev/capi/sa-internal-dev.json | base64 | tr -d '\n') \
>   GCP_CONTROL_PLANE_MACHINE_TYPE=n1-standard-1 \
>   GCP_NODE_MACHINE_TYPE=n1-standard-1 \
>   GCP_REGION=us-central1 \
>   GCP_PROJECT=internal-development-123456\
>   GCP_NETWORK_NAME=kubernetes \
>   clusterctl generate cluster vanilla-2 --flavor gke | kubectl apply -f -
cluster.cluster.x-k8s.io/vanilla-2 created
gcpmanagedcluster.infrastructure.cluster.x-k8s.io/vanilla-2 created
gcpmanagedcontrolplane.infrastructure.cluster.x-k8s.io/vanilla-2-control-plane created
machinepool.cluster.x-k8s.io/vanilla-2-mp-0 created
gcpmanagedmachinepool.infrastructure.cluster.x-k8s.io/vanilla-2-mp-0 created

$ gcloud container node-pools list --cluster=default-vanilla-2-control-plane --region=us-central1
NAME            MACHINE_TYPE  DISK_SIZE_GB  NODE_VERSION
vanilla-2-mp-0  e2-medium     100           1.24.10-gke.2300
```

**What did you expect to happen:**
I expected some CRD to have an option to set the `instanceType` similar to `GCPMachineTemplate` when making a non-managed GCPCluster.

**Anything else you would like to add:**

**Environment:**
- Cluster-api version: v1.4.1
- CAPG version: v1.3.0
- Minikube/KIND version: kind v0.16.0 go1.19.1 darwin/arm64
- Kubernetes version: (use kubectl version): Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
- OS (e.g. from /etc/os-release): MacOS 13.2.1 (22D68) - Darwin Kernel Version 22.3.0

**Comment by lewiscarhartfon** [comment]
I was also unable to find a way of specifying the image template. Would be amazing if this functionality could be added; I think it would be considered a requirement for the tool to work as intended.
